name: First CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Run hello script
      run: ./hello.sh
      run: echo "hello world"
